---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-events-acc
---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  serviceAccountName: monitor-events-acc
  containers:
  - name: shell-operator
    image: linn21/shell-operator:monitor-events
    imagePullPolicy: Always
    env:
    - name: KUBECONFIG
      value: /etc/kubernetes/kube-config.yaml
    volumeMounts:
    - name: kube-config
      mountPath: /etc/kubernetes
  volumes:
  - name: kube-config
    configMap:
      name: kube-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-events
rules:
  - apiGroups: [""]
    resources:
      - pods
      - events
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-events
subjects:
  - kind: ServiceAccount
    name: monitor-events-acc
roleRef:
  kind: Role
  name: monitor-events
  apiGroup: rbac.authorization.k8s.io

